apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base

resources:
- secrets.yml
- persistent-volume.yml
- mysql-deploy.yml
- mysql-service.yml
- flask-api-deploy.yml
- flask-api-service.yml
